version: '3'
services:
    statservice:
      container_name: "statservice"
      build:
        context: ./
        dockerfile: ./Dockerfile
      user: "node"
      volumes:
        - ./src:/home/node/app/src
      networks:
        - default
      links:
        - mongodb
      command: "npm start"

    mongodb:
        container_name: "mongodb"
        image: mongo:latest
        ports:
          - 27018:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        networks:
          - default